Algoritmo "semnome"

Var


   nota1, nota2, notafinal : real


Inicio


      escreva("Digite a primeira nota: ")
      leia(nota1)
      
      escreva("Digite a primeira nota: ")
      leia(nota2)
      
      notafinal <- nota1 + nota2

      escreval("NOTA FINAL: ", notafinal)
      
      se notafinal < 60 entao
         escreval("REPROVADO")
         senao
         escreval("APROVADO")

         
      fimse





Fimalgoritmo
